# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2be3636baf07767dacbb64757cb60dd3d321540a5838a94343e741bc6d78e36f46cb6af5e747801a7f0b706722c9fa2bab8c606df9331cd92582bebac8c8cec5

test:
  secret_key_base: 82070c1cd5e63dcecfe5214239008288da1b31f30dd0d2f08c696f647543bc59c93742512e87534939719a37f026cf66f7f67deaf9f937d7d38fcb31a6945582

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
